# Generated by Django 2.2.16 on 2021-08-28 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210828_1336'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='self_following_disallowed',
        ),
    ]
